### ISSUE TITLE
Lock file is written to persistent volume

### ISSUE THREAD

**Issue by MalikKillian** [dc55028/imapscan#5]
The lock file for `scan_spam.sh` and `learn_spam.sh` is currently written to `/var/spamassassin/scan_lock` which is a persistent volume.  If a container is stopped before this file is cleaned up then it never will be cleaned and these scripts will never start.

It really makes more sense for this file to be created under `/var/lock/` which is a typical location for lock files and a non-persistent path.

**Comment by DominiqueComte** [comment]
The lock file should be better located now.
